### ISSUE TITLE
备份时间判断条件错误

### ISSUE THREAD

**Issue by qingniaoheyu** [celetor/epg#1]
work.js中的149行，备份时间判断多了个2，导致epg中的节目都是未知

**Comment by yue365** [comment]
When using module syntax, the 'fetch' event handler should be declared as an exported function on the root module as opposed to using the global addEventListener().
我对js比较陌生，这个问题怎么解决呢

**Comment by celetor** [comment]
> work.js中的149行，备份时间判断多了个2，导致epg中的节目都是未知

已修正
